### ISSUE TITLE
Handle symlinks

### ISSUE THREAD

**Issue by smashwilson** [atom/watcher#19]
Distinguish and report events relating to symlinks.

- [x] Introduce a `kind: "symlink"` for filesystem events that involve symlinks. (#111)
- [x] When a watch root path containing a symlink is passed to `watchPath()`, report paths to listeners as the symlink path, but disambiguate the watch root using the realpath. (#113)
- [ ] Include a test to be sure we don't lock on up symlink loops. We _shouldn't_ because of the way I'm traversing the filesystem but it pays to be sure. (#114)
- [ ] Include a test for handling broken symlinks gracefully. (#114)

**Comment by smashwilson** [comment]
Notice that this does _not_ include support for `followSymlinks`. I've broken that out to #112 for clarity.
